### ISSUE TITLE
axInput: link.post is not always available

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/laxar_uikit#111] opened 2015-04-16 09:22 UTC
In the control AxInput in line 610 (input.js) the `link.post` is in some cases `undefined`.

**Comment by x1B** [comment] 2015-04-23 11:06
Closing _invalid:_ Cannot reproduce. This seems to have been a setup problem. 

@jonaswjs feel free to reproduce if the problem should occur again

**Closed** 2015-04-23 11:06 UTC
Labels: invalid
